import type { Metadata } from "next";
import "./globals.css";
import "./index.css";
import NavigationHeader from "@/components/layout/NavigationHeader";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/image/logo.png",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <NavigationHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
